'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {Providers} from "./redux/providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <Providers>
        { Pathname !=="/login" && Pathname !=="/not-found"?
        <header>
          <nav className="bg-red-100 flex flex-row justify-end 
">
            <ul>
              <li>
                <Link href="/login">
                <button className="bg-orange-500 text-white px-5 py-2 rounded hover:bg-yellow-700 mr-5 ">
                Login
                  </button>                
                </Link>
                <Link href="/Productlist">
                <button className="bg-violet-500 text-white px-5 py-2 rounded hover:bg-violet-700 ">
                Products
                  </button>                
                </Link>
              </li>
            </ul>
          </nav>
        </header>:
        null
        }
        {children}
        </Providers>
      </body>
    </html>
  );
}
